### all Customers
GET http://localhost:3000/customers

### one custumer
GET http://localhost:3000/customers/1

### create new customer
POST http://localhost:3000/customers
content-type: application/json
  
  {
    "customer_name": "SandroRezende009",
    "email": "sandromelandre@gmail.com",
    "phone": "024993032829",
    "document_type": "CPF",
    "document_number": "01957346701",
    "password": "xptop999",
    "customer_type": "FISICA"
  }

